import { Product } from './types'

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'sample-1',
    name: 'Advanced Snail 96 Mucin Power Essence',
    brand: 'COSRX',
    category: 'serum',
    photo: '',
    description: 'A lightweight essence packed with 96% snail secretion filtrate that repairs, hydrates, and soothes stressed skin. Ideal for rebuilding the skin barrier and achieving a smooth, plump complexion.',
    purchasedPrice: 32.00,
    currency: 'AUD',
    seller: 'YesStyle',
    purchaseDate: '2025-08-15',
    amPm: 'Both',
    usageFrequency: 'Daily',
    howToUse: 'After cleansing and toning, apply a few drops and gently pat into skin until fully absorbed.',
    notes: 'Love layering this under moisturiser on dry skin days.',
    useScenarios: ['express-hydration', 'skin-barrier-recovery'],
    skinConcerns: ['dryness', 'sensitivity-redness', 'uneven-texture', 'skin-barrier-damage'],
    benefits: [
      'Repairs and strengthens the skin barrier',
      'Deeply hydrates without feeling heavy',
      'Soothes redness and irritation',
      'Smooths rough or uneven texture',
    ],
    featuredIngredients: [
      {
        name: 'Snail Secretion Filtrate (96%)',
        riskLevel: 'safe',
        type: 'functional',
        function: 'Skin Repairer / Humectant',
        benefit: 'Accelerates skin recovery, hydrates deeply, and supports collagen production.',
        frequencyGuidance: 'Daily',
      },
      {
        name: 'Sodium Hyaluronate',
        riskLevel: 'safe',
        type: 'functional',
        function: 'Humectant',
        benefit: 'Draws moisture into the skin and helps retain it throughout the day.',
        frequencyGuidance: 'Daily',
      },
      {
        name: 'Betaine',
        riskLevel: 'safe',
        type: 'functional',
        function: 'Humectant / Skin Conditioner',
        benefit: 'Soothes and softens skin, improves hydration levels.',
        frequencyGuidance: 'Daily',
      },
    ],
    createdAt: '2025-08-15T00:00:00.000Z',
    updatedAt: '2025-08-15T00:00:00.000Z',
  },
  {
    id: 'sample-2',
    name: 'AHA BHA PHA 30 Days Miracle Toner',
    brand: 'Some By Mi',
    category: 'toner',
    photo: '',
    description: 'A multi-acid exfoliating toner combining AHA, BHA, and PHA to dissolve dead skin cells, clear congested pores, and reduce blemishes over 30 days of consistent use.',
    purchasedPrice: 22.00,
    currency: 'AUD',
    seller: 'YesStyle',
    purchaseDate: '2025-09-02',
    amPm: 'PM',
    usageFrequency: '2–3x per week (build to nightly)',
    howToUse: 'Apply to a cotton pad and gently wipe over cleansed skin, avoiding the eye area. Use PM only. Start 2–3x per week and slowly increase frequency.',
    notes: 'Very effective on blackheads. Start slow to avoid irritation!',
    useScenarios: ['chemical-exfoliation', 'pore-reduction', 'antibacterial'],
    skinConcerns: ['blackheads', 'inflammatory-acne', 'large-pores', 'uneven-texture', 'hyperpigmentation'],
    benefits: [
      'Unclogs and tightens pores',
      'Removes dead skin cells for a smoother texture',
      'Targets acne-causing bacteria',
      'Fades post-acne marks over time',
    ],
    featuredIngredients: [
      {
        name: 'AHA (Glycolic Acid)',
        riskLevel: 'high-risk',
        type: 'active',
        function: 'Chemical Exfoliant (surface)',
        benefit: 'Dissolves bonds between dead skin cells, improving texture and radiance.',
        frequencyGuidance: '2–3x per week, PM only',
        notes: 'Increases sun sensitivity — always follow with SPF in AM',
      },
      {
        name: 'BHA (Salicylic Acid)',
        riskLevel: 'high-risk',
        type: 'active',
        function: 'Chemical Exfoliant (pore-clearing)',
        benefit: 'Oil-soluble; penetrates pores to dissolve blackheads and reduce congestion.',
        frequencyGuidance: '2–3x per week, PM only',
      },
      {
        name: 'PHA (Gluconolactone)',
        riskLevel: 'moderate',
        type: 'active',
        function: 'Gentle Chemical Exfoliant',
        benefit: 'A milder acid suitable for sensitive skin; exfoliates while hydrating.',
        frequencyGuidance: '2–3x per week',
      },
      {
        name: 'Tea Tree Extract',
        riskLevel: 'moderate',
        type: 'botanical',
        function: 'Antibacterial / Anti-inflammatory',
        benefit: 'Targets acne-causing bacteria and calms inflamed breakouts.',
        frequencyGuidance: 'Daily',
      },
      {
        name: 'Centella Asiatica',
        riskLevel: 'safe',
        type: 'botanical',
        function: 'Skin Soother',
        benefit: 'Calms redness and helps skin recover from acid-induced irritation.',
        frequencyGuidance: 'Daily',
      },
    ],
    createdAt: '2025-09-02T00:00:00.000Z',
    updatedAt: '2025-09-02T00:00:00.000Z',
  },
  {
    id: 'sample-3',
    name: 'No.3 Vitamin C Concentrated Serum',
    brand: 'Numbuzin',
    category: 'serum',
    photo: '',
    description: 'A brightening serum containing a stable form of Vitamin C combined with Niacinamide to fade dark spots, even skin tone, and protect against environmental stressors. Best used in the morning under SPF.',
    purchasedPrice: 45.00,
    currency: 'AUD',
    seller: 'StyleKorean',
    purchaseDate: '2025-07-20',
    amPm: 'AM',
    usageFrequency: 'Daily, AM',
    howToUse: 'Apply 2–3 drops to clean skin after toning. Pat gently until absorbed. Always follow with moisturiser and SPF.',
    notes: 'Store in a cool, dark place to preserve the Vitamin C stability.',
    useScenarios: ['brightening-whitening', 'anti-wrinkle'],
    skinConcerns: ['hyperpigmentation', 'sun-damage', 'uneven-texture'],
    benefits: [
      'Brightens and evens skin tone',
      'Fades dark spots and post-acne marks',
      'Provides antioxidant protection against UV damage',
      'Minimises the appearance of pores',
    ],
    featuredIngredients: [
      {
        name: '3-O-Ethyl Ascorbic Acid (Vitamin C)',
        riskLevel: 'active',
        type: 'active',
        function: 'Antioxidant / Brightener',
        benefit: 'A stable form of Vitamin C that brightens, evens tone, and protects against free radical damage.',
        frequencyGuidance: 'Daily, AM only',
        notes: 'Do not use on the same day as AHA/BHA exfoliants',
      },
      {
        name: 'Niacinamide',
        riskLevel: 'safe',
        type: 'functional',
        function: 'Pore Minimiser / Brightener',
        benefit: 'Reduces enlarged pores, controls sebum, and fades hyperpigmentation.',
        frequencyGuidance: 'Daily',
      },
      {
        name: 'Vitamin E (Tocopherol)',
        riskLevel: 'safe',
        type: 'functional',
        function: 'Antioxidant',
        benefit: 'Works synergistically with Vitamin C to enhance antioxidant protection.',
        frequencyGuidance: 'Daily',
      },
    ],
    createdAt: '2025-07-20T00:00:00.000Z',
    updatedAt: '2025-07-20T00:00:00.000Z',
  },
  {
    id: 'sample-4',
    name: 'Milk Jelly Cleanser',
    brand: 'TIRTIR',
    category: 'cleanser',
    photo: '',
    description: 'A creamy, milk-textured jelly cleanser that gently removes impurities without stripping the skin. Formulated with Ceramides and Centella Asiatica to cleanse while actively supporting the moisture barrier.',
    purchasedPrice: 28.00,
    currency: 'AUD',
    seller: 'Priceline',
    purchaseDate: '2025-10-05',
    amPm: 'Both',
    usageFrequency: 'Daily, AM and PM',
    howToUse: 'Apply a small amount to damp skin, gently massage in circular motions, then rinse with lukewarm water.',
    notes: 'Great for double cleansing — use as the second cleanse after an oil cleanser.',
    useScenarios: ['skin-barrier-recovery', 'express-hydration'],
    skinConcerns: ['dryness', 'sensitivity-redness', 'skin-barrier-damage'],
    benefits: [
      'Cleanses without stripping natural oils',
      'Supports and strengthens the skin barrier',
      'Leaves skin feeling soft and hydrated',
      'Suitable for sensitive or compromised skin',
    ],
    featuredIngredients: [
      {
        name: 'Glycerin',
        riskLevel: 'safe',
        type: 'functional',
        function: 'Humectant',
        benefit: 'Draws moisture into skin during cleansing to prevent dryness.',
        frequencyGuidance: 'Daily',
      },
      {
        name: 'Ceramide NP',
        riskLevel: 'safe',
        type: 'functional',
        function: 'Barrier Repairer',
        benefit: "Replenishes the skin's natural ceramide content to strengthen the moisture barrier.",
        frequencyGuidance: 'Daily',
      },
      {
        name: 'Centella Asiatica Extract',
        riskLevel: 'safe',
        type: 'botanical',
        function: 'Skin Soother / Healer',
        benefit: 'Calms irritation and supports skin repair after cleansing.',
        frequencyGuidance: 'Daily',
      },
    ],
    createdAt: '2025-10-05T00:00:00.000Z',
    updatedAt: '2025-10-05T00:00:00.000Z',
  },
]
